version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: weekly
    target_branch: dev
    automerged_updates:
      - match:
          dependency_type: "development"
    version_requirement_updates: increase_versions
    commit_message:
      prefix: "Change"
